model_list:
  - model_name: gpt-4o-2024-08-06
    litellm_params:
      model: openai/gpt-4o-2024-08-06
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini-2024-07-18
    litellm_params:
      model: openai/gpt-4o-mini-2024-07-18
      api_key: os.environ/OPENAI_API_KEY
