general_settings:
  proxy_batch_write_at: 60
  database_connection_pool_limit: 10
  disable_error_logs: True
  allow_requests_on_db_unavailable: True

litellm_settings:
  request_timeout: 600
  set_verbose: False
